---
- hosts: mongodb
  tasks:
    - name: Install pip
      yum:
        name: python-pip
        state: present
    - name: Install docker-py
      pip:
        name: docker-py
        state: present
    - name: Create mongodb container
      docker_container:
        name: mongodb
        image: mongo:latest
